### ISSUE TITLE
issue with Security monitor configurations and throttling of access to the secure element chip

### ISSUE THREAD

**Issue by KjetilSekse** [Infineon/optiga-trust-m#91]
Currently using an Infineon optiga Trust M V3 together with a microcontroller. Recently we got the need to generate a HMAC every 0.5 seconds and this has been implemented using the optiga_crypt_data_hmac256 which uses the optiga_crypt_hmac(...) function from the optiga library. What has been noticed is that after running it for a while the program slows down significantly until this operation takes a bit over 5 seconds to execute. I have found this to believably be due to the Security monitor configurations which resides in register 0xE0C9 per the solutions reference manual p.102. 

I do however need to change this as timing in the program is critical and this software induced bottleneck is not something I want. It says again at p.102 that the register data can be changed as long as LcsO < 7. I do however not see how this is possible to achieve as the default value for LcsO in the metadata is 7. You do however say in the solutions reference manual at p.90 in the first paragraph : "the default value of t_max is 5 seconds. Due to use case demands, the t_max **can be set to a different value**. Same is said for SEC_credit and SEC_curr. Image taken from the solutions reference manual can be seen below.

![image](https://user-images.githubusercontent.com/26436959/169039184-4bd799b7-43e1-43dc-a883-a8f6cf7568b7.png)

Due to the way the metadata is configured and the fact that the register is in operational state on default I am struggling to see how one could be able to change/configure these values at all? Any help at all in resolving this would be greatly appreciated. 

Best regards

**Comment by sgsharath123** [comment]
Hi @KjetilSekse ,
The chips available in the market have the Security Monitor Configuration object set to operational (LcsO = 7), otherwise it would be a security risk.
"Due to use case demands, the t_max can be set to a different value" - This statement from the Solutions Reference Manual means that for custom orders, the Security Monitor can be configured according to the customer needs. but this has to be done during provisioning in the plant.
In your case, you cannot change the t_max as you have a default market chip and Security Monitor Config object 0xE0E9 is already in operational state (LcsO = 7).
